version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_pma
    depends_on:
      - db
    restart: always
    ports:
      - '8181:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somepassword

  nginx:
    image: nginx:stable-alpine
    container_name: wp_nginx
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/logs/nginx
    ports:
      - '8080:80'

  php:
    image: php:7-fpm-alpine
    container_name: wp_php
    volumes:
      - ./public:/var/www/html
    ports:
      - '9000:9000'

volumes:
  db_data:
